rubrica/urls.py
from django.urls import path
from . import views

app_name = 'rubrica'

urlpatterns = [
    path('', views.index, name='index'),
    path('crear/', views.createRubric, name='crear'),
    path('<int:rubric_id>/ver/', views.seeRubric, name='ver'),
    path('<int:rubric_id>/rm/', views.rm_rubric, name='remover'),
    path('<int:rubric_id>/modificar/', views.modifyRubric, name='modificar'),
]

tarea4/urls.py
import tarea4.settings as settings
from django.contrib import admin
from django.urls import include, path
# from django.contrib.auth.views import LoginView


urlpatterns = [
    path('contact/', include('contact.urls', namespace='contact')),
    path('rubrica/', include('rubrica.urls', namespace='rubrica')),
    path('evaluacion/', include('evaluacion.urls', namespace='evaluacion')),
    path('', include('eabmodel.urls', namespace='main')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('login', name='login')
]

if settings.ADMIN_ENABLED:
    urlpatterns += [
        path('admin/', admin.site.urls),
    ]

rubrica/models.py
from django.db import models


class Rubric(models.Model):
    name = models.CharField(max_length=255)
    min_presentation_time = models.PositiveSmallIntegerField()  # en segundos
    max_presentation_time = models.PositiveSmallIntegerField()  # en segundos
    n_compliance_lvl = models.PositiveSmallIntegerField()
    n_evaluated_aspect = models.PositiveSmallIntegerField()
    rubric = models.TextField()
    completed = models.BooleanField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

rubrica/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.template.defaultfilters import register
from django.urls import reverse

from .models import Rubric
import json

import ast


def index(request):
    created_rubrics = Rubric.objects.order_by("-updated_at")
    return render(request, 'rubrica/index.html', {'rubrics': created_rubrics})

@register.filter(name='split')
def split(value, arg):
    return value.split(arg)


@register.filter(name='clean')
def clean(value):
    return value.split("\', ")[0].split("\'")[-1]


@register.filter(name='aspects')
def aspects(value):

    # rubric = ast.literal_eval(value)

    # rubric = value["rubric"].parse(":")[-1]
    # print(rubric)
    data = json.loads(value)
    # print(data)
    aspects = []

    print(type(data["rubric"]))
    for j, i in enumerate(data["rubric"]):
        if (j!=0):
            aspects.append(i[0])
        # print(type(i))
    return aspects



@register.filter(name='time')
def time(value):
    return str(int(value/60)) + ":" + str(value%60)



def seeRubric(request, rubric_id):
    rubric = get_object_or_404(Rubric, pk=rubric_id)
    data = json.loads(rubric.rubric, encoding='uft-8')

    data = {
        "title": rubric.name,
        "table_data": data["rubric"],
        "status": ("completa" if rubric.completed else "incompleta"),
        "min_presentation_time": rubric.min_presentation_time / 60.0,
        "max_presentation_time": rubric.max_presentation_time / 60.0
    }
    return render(request, 'rubrica/ver.html', context=data)


def createRubric(request):
    if request.method == 'POST':
        json_string = request.body.decode('utf-8')
        data = json.loads(json_string, encoding='utf-8')
        new_rubric = Rubric.objects.create(
            name=data['name'],
            completed=data['completed'],
            n_compliance_lvl=data['n_compliance_lvl'],
            n_evaluated_aspect=data['n_evaluated_aspect'],
            min_presentation_time=data['min_presentation_time'],
            max_presentation_time=data['max_presentation_time'],
            rubric=json_string
        )
        return HttpResponse(new_rubric.id)

    # empty initial table
    data = {
        "title": "",
        "table_data": [["aspecto-tag", "", "", "", ""], ["", "", "", "", ""]],
        "min_presentation_time": 0,
        "max_presentation_time": 0,
    }
    return render(request, 'rubrica/modify.html', context=data)


def modifyRubric(request, rubric_id):
    rubric = get_object_or_404(Rubric, pk=rubric_id)
    if request.method == 'POST':
        json_string = request.body.decode('utf-8')
        data = json.loads(json_string, encoding='utf-8')

        # modify rubric fields
        rubric.name = data['name']
        rubric.completed = data['completed']
        rubric.n_compliance_lvl = data['n_compliance_lvl']
        rubric.n_evaluated_aspect = data['n_evaluated_aspect']
        rubric.min_presentation_time = data['min_presentation_time']
        rubric.max_presentation_time = data['max_presentation_time']
        rubric.rubric = json_string
        rubric.save()

        return HttpResponse(rubric_id)

    # load data
    data = json.loads(rubric.rubric, encoding='uft-8')
    data = {
        "title": rubric.name,
        "table_data": data["rubric"],
        "min_presentation_time": rubric.min_presentation_time / 60.0,
        "max_presentation_time": rubric.max_presentation_time / 60.0
    }
    return render(request, 'rubrica/modify.html', context=data)


def rm_rubric(request, rubric_id):
    ev = get_object_or_404(Rubric, id=rubric_id)
    ev.delete()
    return redirect(reverse("rubrica:index"))

rubrica/templates/rubrica/crear.html
{% extends 'eabmodel/base.html' %}
{#{% load static %}#}


{% block head %}
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.3.min.js"> </script>
    <script>
        function submitform() {
            var rubric = {};
            rubric.name = document.getElementById("rubric-title").value;
            rubric.suggested_presentation_time = Date.now();
            rubric.completed = true;

            var json_table = [];
            var table = document.getElementById("rubric-table");

            for(var i=0; i<table.rows.length; i++) {
                var row = {};
                for(var j=0; j<table.rows[i].cells.length; j++) {
                    //row[document.getElementsByName(i+"-"+j)[0].value] = table.rows[i].cells[j].value;
                    row[i+"-"+j] = document.getElementsByName(i+"-"+j)[0].value; //TODO arreglar
                }
                if (!jQuery.isEmptyObject(row)) {
                    json_table.push(row);
                }
            }
            rubric.n_compliance_lvl = table.rows[0].cells.length;
            rubric.n_evaluated_aspect = table.rows.length - 1;
            rubric.rubric = json_table;
            var jsonString= JSON.stringify(rubric);
            $('<input type="hidden" name="json"/>').val(jsonString).appendTo('#rubric-form');
            $("#rubric-form").submit();
        }

        function isValid() {
            var table = document.getElementById("rubric-table");

            // validate first row as numbers
            for(var j=0; j< table.rows[0].cells.length; i++) {
                if (isNaN(document.getElementsByName(0+"-"+j)[0].value)) {
                    return false;
                };
            }

            // validate sum of scores as 6
            var max_sum = 0;
            for(var i=0; i< table.rows.length; i++) {
                max_sum += parseFloat(table.rows[0].cells[-1].value);
            }

            return max_sum == 6;
        }

        function addRow() {
            var table = document.getElementById("rubric-table");
            var number_rows = table.rows.length;
            var row = table.insertRow(number_rows);
            for(var i=0; i<table.rows[0].cells.length; i++) {
                var newcell = row.insertCell(i);
                var cell_name = number_rows + "-" + i;
                newcell.innerHTML = "<textarea name=" + cell_name +"></textarea>"
            }
        }

        function addColumn() {
            var table = document.getElementById("rubric-table");
            var number_columns = table.rows[0].cells.length;
            for (var i = 0; i < table.rows.length; i++) {
                var newcell = table.rows[i].insertCell(number_columns);
                var cell_name = i + "-" + number_columns;
                newcell.innerHTML = "<textarea name=" + cell_name +"></textarea>"

            }
        }

        function deleteRow() {
            var table = document.getElementById("rubric-table");
            if (table.rows.length > 1) {
                table.deleteRow(-1);
            }
        }

        function deleteColumn() {
            var table = document.getElementById("rubric-table");
            if (table.rows[0].cells.length > 1) {
                for (var i = 0; i < table.rows.length; i++) {
                table.rows[i].deleteCell(-1);
            }

            }
        }

        function onClick(id) {
            console.log('toggling readonly property');
            var element = $("#" + id);
            element.prop('readonly', false); // toggle
        }

        function lostFocus(id) {
            console.log('lostFocust');
            var element = $("#" + id);
            element.prop('readonly', true);
        }

        function setSelectionRange(input, selectionStart, selectionEnd) {
            if (input.setSelectionRange) {
                input.focus();
                input.setSelectionRange(selectionStart, selectionEnd);
            }
            else if (input.createTextRange) {
                var range = input.createTextRange();
                range.collapse(true);
                range.moveEnd('character', selectionEnd);
                range.moveStart('character', selectionStart);
                range.select();
            }
        }

        function setCaretToPos (input, pos) {
            setSelectionRange(input, pos, pos);
        }

    </script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/table-to-json@0.13.0/lib/jquery.tabletojson.min.js" integrity="sha256-AqDz23QC5g2yyhRaZcEGhMMZwQnp8fC6sCZpf+e7pnw=" crossorigin="anonymous"></script>

{% endblock %}

{% block content %}
    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:340px;margin-right:40px">
<form action="" method="post" id="rubric-form" >
        {% csrf_token %}
        <input id="rubric-title" class="w3-xxxlarge w3-text-red" style="margin: 2%;border: none;background: transparent;" value="Título">
{#        <h1 class="w3-xxxlarge w3-text-red" style="margin: 2%;"><b>Ficha de rúbrica</b></h1>#}

        <!DOCTYPE html>
        <div class="w3-row w3-container">
            <div class="w3-col">
                <head>
                    <style>
                        .button2 {
                            background-color: #c6bdbb; /* Green */
                            border: none;
                            color: black;
                            padding: 15px 32px;
                            text-align: center;
                            text-decoration: none;
                            display: inline-block;
                            font-size: 16px;
                            margin: 0.2px 2px;
                            cursor: pointer;
                        }

                        .button2 {width: 50%; border-radius: 12px;}
                        .button2.button2:hover {background-color: #FFA07A;}


                    </style>
                </head>
                <body>
                <button type="button" class="button2 button2" onclick="setCaretToPos(document.getElementById('rubric-table', 4)); onClick('rubric-title')"
                        onblur="lostFocus('rubric-title')"> Título de la rúbrica <i class="fas fa-edit"></i></button><br>
                </body>
            </div>

            <div class = "w3-col" align="right">
                <head>

                    <style>
                        body {font-family: Arial, Helvetica, sans-serif;}

                        .form-inline label {
                            margin: 5px 0 5px 0;
                        }

                        .form-inline input {
                            vertical-align: middle;
                            margin: 5px 10px ;
                            padding: 5px;
                            width: 10%;
                            background-color: #fff;
                            border: 1px solid #ddd;
                        }

                        .form-inline button {
                            padding: 5px 10px;
                            background-color: #c6bdbb;
                            border: none;
                            color: black;
                            cursor: pointer;
                            border-radius: 8px;
                        }

                        .form-inline button:hover {
                            background-color: #FFA07A;
                        }


                    </style>
                </head>
                <body>
{#                <form class="form-inline">#}
{#                    <label>Intervalo de presentación</label>#}
{#                    <input placeholder="Ej: 7-10" name="intervalo">#}
{#                    <button type="submit">Ok</button>#}
{#                </form>#}
                </body>
            </div>
        </div>
    </div>

    <head>
        <style>
            table {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
                cursor: pointer;
                margin: 20px 0.5% 0.5%;
                font-size: 15px;
            }
            textarea {
                width: 100%;
                top: 0; left: 0; right: 0; bottom: 0;
                position: absolute;
                resize: none;
                -webkit-box-sizing: border-box; /* <=iOS4, <= Android  2.3 */
                -moz-box-sizing: border-box; /* FF1+ */
                box-sizing: border-box; /* Chrome, IE8, Opera, Safari 5.1*/
            }
            textarea:focus{
                outline: none;
            }
            td, th {
                border: 1px solid #665f5f;
                text-align: left;
                width: 20%;
                padding: 2.3%;
            }
            table, td, th {
                position: relative;
                border: 1px solid black;
            }

            tr:nth-child(even) {
                background-color: #FFA07A;
            }

        </style>
    </head>
    <body>



        <table id="rubric-table">
            {% if table_data %}
                {% for row in table_data %}
                    <tr>
                        {% for cell_name, cell_content in row %}
                            <td> <textarea name={{ cell_name }}>{{ cell_content }}</textarea> </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            {% endif %}
        </table>

    </form>
    </body>

    <div>
        <head>
            <style>
                .btn-group .button {
                    background-color: #c6bdbb;
                    border: none;
                    color: black;
                    padding: 15px 4.6%;
                    text-align: center;
                    text-decoration: none;
                    display: inline-block;
                    font-size: 16px;
                    cursor: pointer;
                    float: left;
                    margin: 18px 2%;
                }

                .btn-group .button { border-radius: 12px;}

                .btn-group .button:hover { background-color: #FFA07A; }

            </style>
        </head>
        <script>

        </script>
        <body>
        <div class="btn-group">
            <button class="button" onclick="addRow();">Agregar fila  <i class="fas fa-plus"></i></button>
            <button class="button" onclick="addColumn();">Agregar columna <i class="fas fa-plus"></i></button>
            <button class="button" onclick="deleteRow();">Borrar fila  <i class="fas fa-trash"></i></button>
            <button class="button" onclick="deleteColumn();">Borrar columna  <i class="fas fa-trash"></i></button>
        </div>
        </body>
    </div>

    <head>
        <style>
            .button1 {
                background-color: #BF1010;
                border: none;
                color: white;
                padding: 45px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 10px 78%;
                cursor: pointer;
            }

            .button1 {border-radius: 12px;}
            .button1.button1:hover {background-color: #FFA07A;}
        </style>
    </head>
    <body>
    <button type="submit" form="rubric-form" onclick="submitform()" class="button1 button1" id="postbutton">Guardar rúbrica  <i class="far fa-save"></i></button>
{#    <input type="submit" form="rubric-form" value="Guardar rúbrica" class="button1 button1" id="postbutton" onclick="submitform()"/>#}
    </body>





    <!-- End page content -->
    {#</>#}
{% endblock %}

<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px"><p class="w3-right">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></p></div>

</body>
</html>

rubrica/templates/rubrica/index.html
{% extends 'eabmodel/base.html' %}

{% block head %}
{% endblock %}

{% block content %}
    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:340px;margin-right:40px">

    <!-- Portada -->
    <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
      <h1 class="w3-xxxlarge w3-text-red"><b>Rúbricas</b></h1>
      <hr style="width:50px;border:5px solid red" class="w3-round">
    </div>

    {% if user.is_admin %}
    <div class="w3-container">
      <a href="{% url 'rubrica:crear' %}" <button class="w3-button w3-large w3-red w3-right w3-round">Agregar nueva rúbrica</button></a><br>
    </div>
    {% endif %}
    <!--Seccion rubricas-->



    {% for rubric in rubrics %}
        <div>
          <button onclick="toggle({{ rubric.id }})" class="w3-btn w3-red w3-block w3-margin" style="width: 75%">
            <h3>{{ rubric.name }}</h3>
          </button>

            <div id="{{ rubric.id }}" class="w3-hide w3-container w3-pale-red w3-padding-large w3-margin" style="width: 75%">
              <div style="margin-left: 50px">

              {% if rubric.completed %}
                <li style="color: green">Rúbrica Válida
              {% else %}
              <li style="color: red"> Rúbrica Incompleta
               </li>
              {% endif %}

              <li> Creada el {{ rubric.created_at }} </li>
              <li> Última actualización {{ rubric.updated_at }}</li>
              <li>Tiempo Sugerido de Presentación: de {{ rubric.min_presentation_time|time}} a {{ rubric.max_presentation_time|time}} minutos</li>
              <li>Niveles de Cumplimiento: {{ rubric.n_compliance_lvl }}</li>
              <li>Aspectos: {{ rubric.n_evaluated_aspect }} </li>
                  {%  with rubric.rubric|aspects  as aspects %}
                    <ul style="margin-top: 5px;">
                    {%  for aspect in aspects %}
                        <li> {{ aspect }} </li>
                    {% endfor %}
                    </ul>
                  {% endwith %}
              </div>
            <br>
            <br>
              <div style="margin-left: 30px">

                <button class="w3-button w3-large w3-margin-right w3-red w3-left w3-round" onclick="location.href='{{ rubric.id }}/ver'">Ver</button>
                <button class="w3-button w3-large w3-red w3-left w3-round" onclick="location.href='{{ rubric.id}}/modificar'"> Modificar </button>
                <a href="{% url 'rubrica:remover' rubric.id %}" ><button class="w3-button w3-large w3-red w3-right w3-round">Eliminar</button></a>
              </div>
            </div>
        </div>
    {% endfor %}
    </div>

    <script>
      function toggle(name) {
        let x = document.getElementById(String(name));
        if (x.className.indexOf("w3-show") == -1) {
          x.className += " w3-show";
        } else {
          x.className = x.className.replace(" w3-show", "");
        }
      }
    </script>

{% endblock %}

rubrica/templates/rubrica/modify.html
{% extends 'eabmodel/base.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="{% static "rubrica.css" %}">

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"> </script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>

    <script type="text/javascript"> var token = '{{ csrf_token }}'; </script>
    <script type="text/javascript" src = "{% static "rubrica.js" %}"></script>

{% endblock %}

{% block content %}
    <!-- !PAGE CONTENT! -->
    <div id="dialog-confirm" title="¿Seguir editando?">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span></p>
    </div>
    <div class="w3-main" style="margin-left:340px;margin-right:40px">
        <form action="" method="post" id="rubric-form" >
            {% csrf_token %}
            <input id="rubric-title" class="w3-xxxlarge w3-text-red rubric-title" onblur="lostFocus()" readonly placeholder="Título" value="{{ title }}">
            {#        <h1 class="w3-xxxlarge w3-text-red" style="margin: 2%;"><b>Ficha de rúbrica</b></h1>#}

            <!DOCTYPE html>
            <div class="w3-row w3-container">
                <div class="w3-col">
                    <head>
                        <style>
                            .button2 {
                                background-color: #c6bdbb; /* Green */
                                border: none;
                                color: black;
                                padding: 15px 32px;
                                text-align: center;
                                text-decoration: none;
                                display: inline-block;
                                font-size: 16px;
                                margin: 0.2px 2px;
                                cursor: pointer;
                            }

                            .button2 {width: 50%; border-radius: 12px;}
                            .button2.button2:hover {background-color: #FFA07A;}


                        </style>
                    </head>
                    <body>
                    <button type="button" class="button2 button2" onclick="editTitle()"> Título de la rúbrica <i class="fas fa-edit"></i></button><br>
                    </body>


                    <div class = "w3-col" align="right">
                        <head>

                            <style>
                                body {font-family: Arial, Helvetica, sans-serif;}

                                .form-inline label {
                                    margin: 5px 0 5px 0;
                                }

                                .form-inline input {
                                    vertical-align: middle;
                                    margin: 5px 10px ;
                                    padding: 5px;
                                    width: 10%;
                                    background-color: #fff;
                                    border: 1px solid #ddd;
                                }

                                .form-inline button {
                                    padding: 5px 10px;
                                    background-color: #c6bdbb;
                                    border: none;
                                    color: black;
                                    cursor: pointer;
                                    border-radius: 8px;
                                }

                                .form-inline button:hover {
                                    background-color: #FFA07A;
                                }


                            </style>
                        </head>
                        <body>
                        <div class="form-inline">
                            <label>Intervalo de presentación (en minutos)</label> </br>
                            Min: <input style="width: 60px;" placeholder="Ej: 7" id="presentation_min" value={{ min_presentation_time }}>
                            Max: <input style="width: 60px;" placeholder="Ej: 10" id="presentation_max" value={{ max_presentation_time }}>
                        </div>
                        </body>
                    </div>
                </div>
            </div>

            <head>
                <style>
                    table {
                        font-family: arial, sans-serif;
                        border-collapse: collapse;
                        width: 100%;
                        cursor: pointer;
                        margin: 20px 0.5% 0.5%;
                        font-size: 15px;
                        table-layout: fixed ;
                    }
                    textarea {
                        width: 100%;
                        height: 100%;
                        top: 0; left: 0; right: 0; bottom: 0;
                        padding: 5px;
                        position: absolute;
                        resize: none;
                        -webkit-box-sizing: border-box; /* <=iOS4, <= Android  2.3 */
                        -moz-box-sizing: border-box; /* FF1+ */
                        box-sizing: border-box; /* Chrome, IE8, Opera, Safari 5.1*/
                    }
                    textarea:focus{
                        outline: none;
                    }
                    td, th {
                        border: 1px solid #665f5f;
                        text-align: left;
                        width: 20%;
                        padding: 2.3%;
                        height: 100px;
                    }
                    table, td, th {
                        position: relative;
                        border: 1px solid black;
                    }

                    tr:nth-child(even) {
                        background-color: #FFA07A;
                    }

                </style>
            </head>
            <body>

            <span id="status"> Status: </span> <span id="status-rubrica">   </span>

            <table id="rubric-table">
                {% if table_data %}
                    {% for row in table_data %}
                        <tr>
                            {% for cell_content in row %}
                                {% if cell_content == "aspecto-tag" or cell_content == null %}
                                    <td> <b> Aspecto\Puntaje </b> </td>
                                {% else %}
                                    <td> <textarea >{{ cell_content }}</textarea> </td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>


            </body>
        </form>
        <div>
            <head>
                <style>
                    .btn-group .button {
                        background-color: #c6bdbb;
                        border: none;
                        color: black;
                        padding: 15px 4.6%;
                        text-align: center;
                        text-decoration: none;
                        display: inline-block;
                        font-size: 16px;
                        cursor: pointer;
                        float: left;
                        margin: 18px 2%;
                    }

                    .btn-group .button { border-radius: 12px;}

                    .btn-group .button:hover { background-color: #FFA07A; }

                </style>
            </head>

            <body>
            <br>
            <div class="btn-group">
                <button class="button" onclick="addRow();">Agregar fila  <i class="fas fa-plus"></i></button>
                <button class="button" onclick="addColumn();">Agregar columna <i class="fas fa-plus"></i></button>
                <button class="button" onclick="deleteRow();">Borrar fila  <i class="fas fa-trash"></i></button>
                <button class="button" onclick="deleteColumn();">Borrar columna  <i class="fas fa-trash"></i></button>
            </div>
            </body>
        </div>

        <head>
            <style>
                .button1 {
                    background-color: #BF1010;
                    border: none;
                    color: white;
                    padding: 45px;
                    text-align: center;
                    text-decoration: none;
                    display: inline-block;
                    font-size: 16px;
                    margin: 10px 78%;
                    cursor: pointer;
                }

                .button1 {border-radius: 12px;}
                .button1.button1:hover {background-color: #FFA07A;}
            </style>
        </head>
        <body>
        <button type="submit" form="rubric-form" class="button1 button1" id="postbutton">Guardar rúbrica  <i class="far fa-save"></i></button>
        </body>





        <!-- End page content -->
        {#</>#}
    </div>
{% endblock %}

<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px"><p class="w3-right">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></p></div>