evaluacion/urls.py
from django.urls import path

from . import views

app_name = 'evaluacion'

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add_evaluation, name='add'),
    path('edit/<int:id>', views.edit_evaluation, name='edit'),
    path('view/<int:id>', views.view_evaluation, name='view'),
    path('rm/<int:id>', views.rm_evaluation, name='remove'),
    path('eval/<str:name>/<str:course>/<str:section>/<str:semester>/<str:year>/<str:team>', views.openEval, name='evaluacion'),
    path('evalAdmin/<str:name>/<str:course>/<str:section>/<str:semester>/<str:year>/<str:team>', views.openEvalAdmin, name='evaluacionAdmin'),
    path('evalAdmin/<int:id>', views.openEvalAdmin2, name='evaluacionAdmin'),
    path('postEval/<str:name>/<str:course>/<str:section>/<str:semester>/<str:year>/<str:team>', views.postEval, name='postEval'),
    path('postEvalAdmin/<str:name>/<str:course>/<str:section>/<str:semester>/<str:year>/<str:team>', views.postEvalAdmin, name='postEvalAdmin'),
    path('<int:id>/addEvaluator/', views.add_evaluator_view, name='addevaluator'),
    path('<int:id>/editRubric/', views.edit_rubric, name='editRubric'),
    path('<int:id>/editDates/', views.edit_dates, name='editDates'),
    path('add_evaluator/', views.add_evaluator, name='add_evaluator'),
    path('rm/<int:eva_id>/<int:ev_id>', views.rm_evaluator, name='rm_evaluator'),
    path('<int:id>/open/', views.open_evaluation, name='open_eval'),

]

rubrica/urls.py
from django.urls import path
from . import views

app_name = 'rubrica'

urlpatterns = [
    path('', views.index, name='index'),
    path('crear/', views.createRubric, name='crear'),
    path('<int:rubric_id>/ver/', views.seeRubric, name='ver'),
    path('<int:rubric_id>/rm/', views.rm_rubric, name='remover'),
    path('<int:rubric_id>/modificar/', views.modifyRubric, name='modificar'),
]

tarea4/urls.py
import tarea4.settings as settings
from django.contrib import admin
from django.urls import include, path
# from django.contrib.auth.views import LoginView


urlpatterns = [
    path('contact/', include('contact.urls', namespace='contact')),
    path('rubrica/', include('rubrica.urls', namespace='rubrica')),
    path('evaluacion/', include('evaluacion.urls', namespace='evaluacion')),
    path('', include('eabmodel.urls', namespace='main')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('login', name='login')
]

if settings.ADMIN_ENABLED:
    urlpatterns += [
        path('admin/', admin.site.urls),
    ]

evaluacion/models.py
from django.db import models

from eabmodel.models import Student, Course, Team
from users.models import EvaluatorUser
from rubrica.models import Rubric

# Create your models here.


class Evaluation(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    
    name = models.CharField(max_length=255)
    date = models.DateTimeField()
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    rubric = models.ForeignKey(Rubric, on_delete=models.PROTECT)
    presentation_time = models.TimeField()
    evaluators = models.ManyToManyField(EvaluatorUser)
    is_active = models.BooleanField(default=False)

    def get_year(self):
        return self.date.year

    class Meta:
        unique_together = ["name", "date", ]


class TeamEvaluation(models.Model):

    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    evaluation = models.ForeignKey(Evaluation, models.PROTECT)
    presenter = models.ManyToManyField(Student)
    # start_time = models.DateTimeField()
    # end_time = models.DateTimeField()
    duration = models.PositiveSmallIntegerField()
    is_active = models.BooleanField(default=False)


class TeamEvaluationGrade(models.Model):

    submitted_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    team_evaluation = models.ForeignKey(TeamEvaluation, on_delete=models.CASCADE)
    evaluator = models.ForeignKey(EvaluatorUser, on_delete=models.PROTECT)
    grade_detail = models.TextField()
    final_grade = models.FloatField()
    comment = models.TextField()

evaluacion/forms.py
from django import forms

from .models import Evaluation
from users.models import EvaluatorUser
from rubrica.models import Rubric

class EvaluationForm(forms.ModelForm):
    class Meta:
        model = Evaluation
        fields = [
            'name',
            'date',
            'final_date',
            'course',
            'rubric',
            'presentation_time',
        # 'evaluators',
        # 'is_active'
        ]
        # widgets = { }


class AddEvaluatorForm(forms.ModelForm):
    class Meta:
        model = Evaluation
        fields = ('evaluators',)

class AddEvaluatorForm2(forms.Form):
    evaluator_id = forms.IntegerField()
    # evaluation_id = forms.IntegerField()



class EditRubricForm(forms.ModelForm):
    #rubricas = forms.ChoiceField(choices=[(rubrica.id, rubrica.rubric) for rubrica in Rubric.objects.all()])
    #rubricas = forms.ModelChoiceField(queryset=Rubric.objects.all())
    class Meta:
        model = Evaluation
        fields = ('rubric',)
        #widgets = { 'rubricas': forms.Select(attrs={'class':'select'})
        #}

class EditDatesForm(forms.ModelForm):
    class Meta:
        model = Evaluation
        fields = [
        'date',
        'final_date'
        ]

evaluacion/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required, user_passes_test

from evaluacion.forms import EvaluationForm, AddEvaluatorForm, AddEvaluatorForm2
from evaluacion.models import *
from eabmodel.models import *
from users.models import *
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponseForbidden, HttpResponseNotFound
import json


@login_required
def index(request, extra_context={}):

    if(request.user.is_admin):
        # pass
        evaluations = Evaluation.objects.all()
    else:
        evaluations = Evaluation.objects.all().filter(evaluators=request.user)

    context = {'evaluations': evaluations, 'form': EvaluationForm(prefix="agregar")}
    context.update(extra_context)
    return render(request, 'evaluacion/index.html', context)

@login_required
def view_evaluation(request, id):
    evaluation = get_object_or_404(Evaluation, id=id)
    context = {'evaluation': evaluation}
    return render(request, 'evaluacion/verEval.html', context)

@login_required
def edit_evaluation(request, id):
    evaluation = get_object_or_404(Evaluation, id=id)
    context = {'evaluation': evaluation}
    return render(request, 'evaluacion/verEval.html', context)

def rm_evaluation(reques, id):
    ev = get_object_or_404(Evaluation, id=id)
    ev.delete()
    return redirect(reverse("evaluacion:index"))


@login_required
def add_evaluation(request):
    extra_context = {}


    if not request.user.is_admin:
        return HttpResponseNotFound('Sorry')

    if request.method != 'POST':
        form = EvaluationForm(prefix="agregar")

    else:
        form = EvaluationForm(request.POST, prefix="agregar")
        if form.is_valid():
            form.save()
        else:
            print(form.errors)

    # form
    extra_context.update({'form': form})
    response = index(request, extra_context)
    return response



@csrf_exempt
def openEval(request, name, course, section, semester, year, team):

    semester_name = getSemester(semester)
    if request.method == 'POST':
        json_string = request.body.decode('utf-8')
        data = json.loads(json_string, encoding='utf-8')
        gdet = json.loads(data['grade_detail'], encoding='utf-8')
        course_obj = get_object_or_404(Course, code=course, section=section, year=year, semester=semester_name)
        evaluation = get_object_or_404(Evaluation, name=name, course=course_obj)
        team_evaluated = get_object_or_404(Team, id=team)
        evaluator = get_object_or_404(EvaluatorUser, id=1)
        teamEval = get_object_or_404(TeamEvaluation, team=team_evaluated, evaluation=evaluation)
        gDetail = dict()
        grade = 1
        for ac in gdet:
            gDetail[ac[0]] = ac[2]
            grade += ac[2]
        TeamEvaluationGrade.objects.create(submitted_at=data['submitted_at'],
                                           updated_at=data['updated_at'],
                                           team_evaluation=teamEval,
                                           evaluator=evaluator,
                                           grade_detail=json.dumps(gDetail),
                                           final_grade=grade)
        return JsonResponse(gDetail)
    else:
        curso = get_object_or_404(Course, code=course, section=section, semester=semester_name, year=year)
        equipo = get_object_or_404(Team, id=team, course=curso.id)
        evalActual = get_object_or_404(Evaluation, name=name, course=curso)
        if not TeamEvaluation.objects.filter(team=equipo, evaluation=evalActual).exists():
            return HttpResponseBadRequest("<div style='text-align:center'>La evaluación para este equipo aún no está "
                                          + "disponible. Por favor espere"
                                          + " hasta que el/la profesor/a comience esta evaluación.</div>"
                                          + "<div style='text-align:center'><a href=http://localhost:8000/evaluacion>"
                                          + "Volver al Menú de Evaluaciones</a></div>")
        if request.user not in evalActual.evaluators.all():
            return HttpResponseForbidden("<div style='text-align:center'>Usted no está asignado para esta evaluación. "
                                         + "Si cree que esto es un error comuníquese con el/la profesor/a "
                                         + "a cargo.</div>"
                                         + "<div style='text-align:center'><a href=http://localhost:8000/evaluacion>"
                                         + "Volver al Menú de Evaluaciones</a></div>")
        try:
            parsedRub = json.loads(evalActual.rubric.rubric)
        except(ValueError, KeyError, TypeError):
            print("Error en Formato de Rúbrica")
            return HttpResponseBadRequest("Error en Formato de Rúbrica")
        rubrica = getRubrica2(parsedRub["rubric"])
        context = dict()
        context['team'] = equipo.name
        context['stage'] = evalActual.name
        context['course'] = course
        context['section'] = section
        context['year'] = year
        context['rubric'] = rubrica
        context['numberOfAspects'] = len(rubrica)
        context['team_id'] = team
        context['semester'] = semester_name
        context['semester_code'] = semester
        return render(request, 'evaluacion/evaluacion.html', context=context)

@csrf_exempt
def openEvalAdmin(request, name, course, section, semester, year, team):

    semester_name = getSemester(semester)


    if request.method == 'POST':
        json_string = request.body.decode('utf-8')
        data = json.loads(json_string, encoding='utf-8')
        gdet = json.loads(data['grade_detail'], encoding='utf-8')
        presenters = json.loads(data['presenters'], encoding='utf-8')
        course_obj = get_object_or_404(Course, code=course, section=section, year=year, semester=semester_name)
        evaluation = get_object_or_404(Evaluation, name=name, course=course_obj)
        team_evaluated = get_object_or_404(Team, id=team)
        teamEval = get_object_or_404(TeamEvaluation, team=team_evaluated, evaluation=evaluation)
        for pres in presenters:
            teamEval.presenter.add(Student.objects.get(id=pres[1]))
        gDetail = dict()
        grade = 1
        for ac in gdet:
            gDetail[ac[0]] = ac[2]
            grade += ac[2]
        discs = encodeDiscount(evaluation.rubric.max_presentation_time, evaluation.rubric.min_presentation_time,
                               getSeconds(data['time']))
        gDetail['Time'] = discs[0]
        gDetail['Type'] = discs[1]
        TeamEvaluationGrade.objects.create(submitted_at=data['submitted_at'],
                                           updated_at=data['updated_at'],
                                           team_evaluation=teamEval,
                                           evaluator=request.user,
                                           grade_detail=json.dumps(gDetail),
                                           final_grade=grade)
        return JsonResponse(gDetail)

    else:

        curso = get_object_or_404(Course, code=course, section=section, semester=semester_name, year=year)
        equipo = get_object_or_404(Team, id=team, course_id=curso.id)
        evalActual = get_object_or_404(Evaluation, name=name, course=curso)
        if not TeamEvaluation.objects.filter(team=equipo, evaluation=evalActual).exists():
            return HttpResponseBadRequest("<div style='text-align:center'> La evaluación para este equipo aún no está"
                                          + " disponible. Puede comenzarla en el"
                                          + " <a href=http://localhost:8000/evaluacion/>menú de evaluaciones</a> si lo"
                                          + " desea.</div>")
        try:
            parsedRub = json.loads(evalActual.rubric.rubric)
            print(parsedRub['rubric'])
        except(ValueError, KeyError, TypeError):
            print("Error en Formato de Rúbrica")
            return HttpResponseBadRequest("Error en Formato de Rúbrica")

        rubrica = getRubrica2(parsedRub['rubric'])
        alreadyPresented = []
        presenting_group = []

        for ev in TeamEvaluation.objects.filter(team=equipo):
            for alumn in ev.presenter.all():
                name = alumn.first_name + " " + alumn.last_name
                alreadyPresented.append(name)
        for a in StudentAtTeam.objects.filter(team=equipo.id, active=True):
            student_name = a.student.first_name + " " + a.student.last_name
            if student_name in alreadyPresented:
                pres = True
            else:
                pres = False
            presenting_group.append([student_name, pres, a.student.id])
        context = dict()
        context['group'] = presenting_group
        context['team'] = equipo.name
        context['team_id'] = team
        context['course'] = course
        context['section'] = section
        context['semester_code'] = semester
        context['year'] = year
        context['semester'] = semester_name
        context['stage'] = evalActual.name
        context['evaluation'] = evalActual
        context['rubric'] = rubrica
        context['evaluators'] = [["Jocelyn Simmonds", False], ["Pablo Miranda", True]]
        return render(request, 'evaluacion/evaluacionadmin.html', context=context)


def openEvalAdmin2(request, id):
    a = Evaluation.objects.get(pk=id)
    name = a.name

    print(a.course)
    course = a.course.code
    section = a.course.section
    semester = a.course.semester
    year = a.course.year
    team = 1
    return openEvalAdmin(request, name, course, section, semester[0], year, team)

@login_required
def postEval(request, name, course, section, semester, year, team):

evaluacion/templates/evaluacion/addevaluator.html
{% extends "eabmodel/base.html" %}

{% block subtitle %}Añadir evaluador{% endblock %}

{% block content %}

<body>
<link rel="stylesheet" type="text/css" href="./evaluacion.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">
  <!-- Photo grid (modal) -->



  <!-- Evaluacion -->
  <div class="w3-container" id="designers" style="margin-top:50px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Evaluación
      {% if evaluation.is_active == True %}
      <i class="w3-text-green">en curso</i> </b></h1>
      {% else %}
      <i class="w3-text-orange">cerrada</i> </b></h1>
      {% endif %}
    <hr style="width:50px;border:5px solid red" class="w3-round">
    <div class="w3-container ">

    <ul>
    <li><b>Presentación:  </b>{{ evaluation.name|title }} <i> {{ evaluation.course.code|upper }} / {{ evaluation.course.semester|title }} / {{ evaluation.course.year }}</i></li>
    <li><b>Fecha de inicio:</b> <i>{{ evaluation.date|date:"SHORT_DATE_FORMAT" }}</i></li>
    <li><b>Fecha de término:</b> <i>{{ evaluation.final_date|date:"SHORT_DATE_FORMAT" }}</i></li>
    <li><b>Tiempo de presentación:</b> <i>{{ evaluation.presentation_time }}</i></li>
    <li><b>Rúbrica:</b><i>{{ evaluation.rubric.name }}</i></li>

      {% if evaluation.is_active == False%}
        {% if grades.count == 0 %}
      <!--<button class="w3-button w3-large w3-red w3-round" onclick="window.location.href="{{ evaluation.id }}/editRubric/" >Editar rúbrica</button>-->
        <a href="{% url 'evaluacion:editRubric' id=evaluation.id %}" >Editar rúbrica</a>
        {% endif %}
      {% endif %}

    </ul>
      <!--<ul id="rubricas">
{#        {% for rubric in rubrics %}#}
              <li class="w3-padding-16"><a href="google.com">rubric.rubric</a></li>
{#        {% endfor %}#}
        </ul> -->

      
    <br>
  {% if user.is_admin %}

   <div class="w3-panel  w3-margin-bottom">
      <ul class="w3-ul w3-light-grey w3-center w3-card-4">
        <li class="w3-dark-grey w3-xlarge w3-padding-32">Evaluadores <i class="fas fa-user-tie"></i> </li>
          {% for evaluator in evaluators %}
                  <li class="w3-padding-16">{{ evaluator.first_name }} {{ evaluator.last_name }}
                    <a href="{% url 'evaluacion:rm_evaluator'  evaluation.id evaluator.id %}" ><button style="margin-left: 10px" class="w3-large fas fa-times"></button></a>
                  </li>

          {% endfor %}
        <button onclick="showEvaluators()" class="opcion w3-padding-16" style="width: 100%"> Editar evaluadores <i style="margin-left: 10px" class="fas fa-user-plus"></i></button>
      </ul>

     <form id=evaluadores action='.' method='POST'>
       {% csrf_token %}
      <table>
        <tr><th><label for="id_evaluators">Evaluators:</label></th><td><select name="evaluators" id="id_evaluators" multiple="">
            {% for i in all_evaluator %}
              <option value="{{ i.id }}">{{ i.first_name }}  {{ i.last_name }} ( {{ i.email }})</option>
            {% endfor %}
        </select></td></tr>
      </table>
    <input type='submit' value='Save' />
  </form>

     <script>document.getElementById("evaluadores").style.display = "none";</script>

     <br>
    </div>

    {% endif %}

    {% if evaluation.is_active %}
    <div class="w3-row-padding" style="margin-top:100px">
      <div class="w3-half w3-margin-bottom ">
          <ul class="w3-ul w3-light-grey w3-center w3-card-4">
            <li class="w3-red w3-xlarge w3-padding-32">Equipos pendientes<i style="margin-left: 10px" class="fas fa-user-friends"></i><br> <i class="w3-small">Comience una nueva evaluación...</i></li>
            {% for team in left_teams %}
              <li class="opcion w3-padding-16">{{ team.0 }}
{#                <a href="{% url 'evaluacion:evaluacionAdmin' name=evaluation.name course=evaluation.course.code section=evaluation.course.section semester=evaluation.course.semester|make_list|first year=evaluation.course.year team=team.1 %}">#}
                {% if user.is_admin %}
                <button style="margin-left: 10px" class="w3-xlarge fas fa-play-circle" class="w3-button w3-xlarge w3-red w3-margin-bottom" style="margin-left: 17%" onclick="evaluateGroup({{ team.1}})"> </button></li>
              {% else %}
                  <button style="margin-left: 10px" class="w3-xlarge fas fa-play-circle" class="w3-button w3-xlarge w3-red w3-margin-bottom" style="margin-left: 17%" onclick="evaluateGroupNoAdmin({{ team.1}})"> </button></li>
              {% endif %}
            {% endfor %}
          </ul>
      </div>
    {% else %}
        <div class="w3-container w3-left" style="width: 100%">
        {% if user.is_admin %}
            <p class="w3-text-red"><b>La evaluación no está abierta, ¿Desea abrirla?</b></p>
            <button class="w3-button w3-xlarge w3-blue" style="margin-left: 5%; float: left" onclick="openEval({{ evaluation.id }})">Abrir evaluación</button>
          {% else %}
            <p class="w3-text-red"><b>La evaluación no está abierta</b></p>
          {% endif %}
        </div>
    {% endif %}

  {%  if user.is_admin %}
      <div class="w3-container" style="width: 100%" >
          <button class="w3-button w3-xlarge w3-red w3-margin-bottom" style="margin-left: 17%; float: right" <i class="fas fa-pen"></i>  Editar evaluación</button>
  {% endif %}
      </div>
  </div>

    <br>
    <br>



<!-- End page content -->
</div>












</body>

    <script>
        var x = 0;
        function showEvaluators(){
            if(x == 0){
                document.getElementById("evaluadores").style.display="block";
                x = 1;
            }else{
                document.getElementById("evaluadores").style.display="none";
                x = 0;
            }
        }

        var y = 0;
        function editRubric(){
            if(x == 0){
                document.getElementById("rubricas").style.display="none";
                y = 1;
            }else{
                document.getElementById("rubricas").style.display="block";
                y = 0;
            }
        }


        function evaluateGroup(id){
            dataToSend = {};
            dataToSend.func = "evaluateGroup";
            dataToSend.team = id;
            var xhttp = new XMLHttpRequest();

            var sem = "{{ evaluation.course.semester }}"[0];

            {#xhttp.onreadystatechange = function(){#}
            {#    if (this.readyState == 4){#}
            {#        if(this.status == 200){#}
            window.location.replace("http://localhost:8000/evaluacion/evalAdmin/{{ evaluation.name }}/{{ evaluation.course.code}}/{{ evaluation.course.section }}/"+ sem +"/{{ evaluation.course.year }}/" + id.toString());
            {#        }#}
            {#        else{#}
            {#            alert("Falló la creación de la evaluación. Por favor intente nuevamente.")#}
            {#        }#}
            {#    }#}
            {# ; #}
            {#xhttp.open('POST', "http://localhost:8000/evaluacion/evalAdmin/{{ evaluation.name }}/{{ evaluation.course.code}}/{{ evaluation.course.section }}/"+ sem +"/{{ evaluation.course.year }}/" + id.toString(), true);#}
            {#xhttp.setRequestHeader('Content-Type', 'text/plain; charset="utf-8"');#}
            {#xhttp.send(JSON.stringify(dataToSend));#}
        }

        function evaluateGroupNoAdmin(id){
            dataToSend = {};
            dataToSend.func = "evaluateGroup";
            dataToSend.team = id;
            var xhttp = new XMLHttpRequest();

            var sem = "{{ evaluation.course.semester }}"[0];
            window.location.replace("http://localhost:8000/evaluacion/eval/{{ evaluation.name }}/{{ evaluation.course.code}}/{{ evaluation.course.section }}/"+ sem +"/{{ evaluation.course.year }}/" + id.toString());
        }



        function openEval(id){
            dataToSend = {};
            dataToSend.func = "openEval";
            dataToSend.id = id;
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function(){
                if (this.readyState == 4){
                    if(this.status == 200){
                        location.reload();
                    }
                    else{
                        alert("Falló la apertura de la evaluación. Por favor intente nuevamente.")
                    }
                }
            };
            xhttp.open('POST', '/evaluacion/{{ evaluation.id }}/open/', true);
            xhttp.setRequestHeader('Content-Type', 'text/plain; charset="utf-8"');
            xhttp.send(JSON.stringify(dataToSend));
        }

    </script>

{% endblock content %}

evaluacion/templates/evaluacion/editdates.html
{% extends "eabmodel/base.html" %}

{% block subtitle %}Añadir evaluador{% endblock %}

{% block content %}

<body>
<link rel="stylesheet" type="text/css" href="./evaluacion.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Evaluación {{ evaluation.name }} <i> </b></i></b></h1>


  <!-- Photo grid (modal) -->

      <form action='.' method='POST'>{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save' />
</form>
    <br>
    </div>


<!-- End page content -->
</div>

<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px"><p class="w3-right">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></p></div>

</body>
{% endblock content %}

evaluacion/templates/evaluacion/editrubric.html
{% extends "eabmodel/base.html" %}

{% block subtitle %}Añadir evaluador{% endblock %}

{% block content %}

<body>
<link rel="stylesheet" type="text/css" href="./evaluacion.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Evaluación {{ evaluation.name }} <i> </b></i></b></h1>


  <!-- Photo grid (modal) -->

      <form action='.' method='POST'>{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Editar' />
</form>
    <br>
    </div>


<!-- End page content -->
</div>

<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px"><p class="w3-right">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></p></div>

</body>
    <script>
        var y = 0;
        function editRubric(){
            if(x == 0){
                document.getElementById("rubricas").style.display="none";
                y = 1;
            }else{
                document.getElementById("rubricas").style.display="block";
                y = 0;
            }
        }

    </script>

{% endblock content %}