contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='info'),
]

eabmodel/urls.py
from django.urls import path, include

from . import views

app_name='main'

urlpatterns = [
    path('contact/', include('contact.urls', namespace='contact')),
    path('evaluaciones/', include('evaluacion.urls', namespace='evaluaciones')),
    path('rubricas/', include('rubrica.urls', namespace='rubricas')),
    path('', views.landingpage, name='landing_page'),

    path('courses', views.courses, name='courses'),
    path('add_course', views.add_course, name='add_course'),
    path('rm_course', views.remove_course, name='remove_course'),
    path('modify_course', views.modify_course, name='modify_course'),
    path('modify_course/<int:course>', views.modify_course, name='modify_course'),

    path('evaluators', views.evaluators, name='evaluators'),
    path('modify_eval', views.modify_eval, name='modify_eval'),
    path('modify_eval/<int:eval>', views.modify_eval, name='modify_eval'),
    path('add_eval', views.add_eval, name='add_eval'),
    path('rm_eval', views.remove_eval, name='remove_eval'),
]

rubrica/urls.py
from django.urls import path
from . import views

app_name = 'rubrica'

urlpatterns = [
    path('', views.index, name='index'),
    path('crear/', views.createRubric, name='crear'),
    path('<int:rubric_id>/ver/', views.seeRubric, name='ver'),
    path('<int:rubric_id>/rm/', views.rm_rubric, name='remover'),
    path('<int:rubric_id>/modificar/', views.modifyRubric, name='modificar'),
]

tarea4/urls.py
import tarea4.settings as settings
from django.contrib import admin
from django.urls import include, path
# from django.contrib.auth.views import LoginView


urlpatterns = [
    path('contact/', include('contact.urls', namespace='contact')),
    path('rubrica/', include('rubrica.urls', namespace='rubrica')),
    path('evaluacion/', include('evaluacion.urls', namespace='evaluacion')),
    path('', include('eabmodel.urls', namespace='main')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('login', name='login')
]

if settings.ADMIN_ENABLED:
    urlpatterns += [
        path('admin/', admin.site.urls),
    ]

eabmodel/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import ugettext_lazy as _

from users.models import EvaluatorUser


# Create your models here.
class Course(models.Model):
    code = models.CharField('código', max_length=7, help_text=_('código del curso'))
    name = models.CharField('nombre', max_length=150, help_text=_('nombre del curso'))
    section = models.PositiveSmallIntegerField('sección', default=1, help_text=_('sección del curso'), validators=[MinValueValidator(1), MaxValueValidator(30)])
    year = models.PositiveSmallIntegerField('año', default=2019, help_text=_('año que se dicta el curso'))

    SEMESTER_CHOICES = (
        ('Otoño', 'Otoño'),
        ('Primavera', 'Primavera'),
        ('Verano', 'Verano'),
    )
    semester = models.CharField(max_length=9, choices=SEMESTER_CHOICES, default='Otoño', help_text=_('semestre que se dicta el curso'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    evaluators = models.ManyToManyField(EvaluatorUser, blank=True)

    class Meta:
        unique_together = ["code", "section", "year", "semester"]
        verbose_name = 'curso'
        verbose_name_plural = 'cursos'

class Student(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    # run = models.IntegerField() # es necesario?
    course = models.ForeignKey(Course, on_delete=models.PROTECT)

    class Meta:
        unique_together = ["first_name", "last_name", "course"]


class Team(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=255)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    active = models.BooleanField()

    class Meta:
        unique_together = ["name", "course"]


class StudentAtTeam(models.Model):
    join_date = models.DateTimeField(auto_now_add=True)
    left_date = models.DateTimeField(blank=True, null=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

eabmodel/forms.py
from django import forms
from .models import Course
from datetime import datetime


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'code',  'section', 'year', 'semester']

    def clean(self):
        cleaned_data = super().clean()
        year = cleaned_data.get('year')

        if year < datetime.now().year or year > datetime.now().year+1:
            raise forms.ValidationError(
               "Solo puedes crear cursos de este año o el siguiente"
            )
        cleaned_data['code'] = cleaned_data.get('code').upper()
        return cleaned_data


class RemoveCourseForm(forms.Form):
    id = forms.IntegerField()


class ModifyCourseForm(CourseForm):
    pass

eabmodel/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseNotFound

from users.models import EvaluatorUser
from users.forms import EvaluatorUserCreationForm, EvaluatorUserRemoveForm, EvaluatorUserChangeForm

from .models import Course
from .forms import CourseForm, RemoveCourseForm, ModifyCourseForm


# Create your views here.
from evaluacion.models import Evaluation


@login_required
def landingpage(request):
    evaluations = Evaluation.objects.order_by("-date")
    if len(evaluations) > 10:
        evaluations = evaluations[:10]
    return render(request, 'eabmodel/landingpage.html', {'top10_eval': evaluations})


@login_required
def courses(request, extra_context={}):
    context = {'is_admin': False}

    if not request.user.is_admin:
        course_list = Course.objects.all().filter(evaluators=request.user).order_by('updated_at', 'created_at').reverse()

    else:
        form = CourseForm(prefix='agregar')
        course_list = Course.objects.all().order_by('updated_at', 'created_at').reverse()
        context.update({'form': form, 'is_admin': True})

    context.update({'course_list': course_list, 'modify_form': ModifyCourseForm(prefix="modificar")})

    context.update(extra_context)
    return render(request, 'eabmodel/course.html', context)


@login_required
def add_course(request):
    extra_context = {}

    if not request.user.is_admin:
        return HttpResponseNotFound('Sorry')

    if request.method != 'POST':
        form = CourseForm(prefix="agregar")

    else:
        form = CourseForm(request.POST, prefix="agregar")
        if form.is_valid():
            added_course = form.save()
            extra_context.update({'added_course': added_course, 'added_msg': True})
# form
    extra_context.update({'form': form})
    response = courses(request, extra_context)
    return response

@login_required
def modify_course(request, course=None):
    extra_context ={}

    if course is not None:
        if not request.user.is_admin:
            return HttpResponseNotFound('Sorry')

        if request.method == 'POST':
            new_form = ModifyCourseForm(request.POST, instance=Course.objects.get(pk=course), prefix="modificar",)

            if new_form.is_valid():
                new_form.save()

            extra_context.update({'modify_form': new_form})

    response = courses(request, extra_context)
    return response



@login_required
def remove_course(request):

    if not request.user.is_admin:
        return HttpResponseNotFound('Sorry')

    if request.method == 'POST':
        form = RemoveCourseForm(request.POST)
        if form.is_valid():
            course = Course.objects.get(pk=form.cleaned_data['id'])
            course.delete()
    return redirect(reverse('main:courses'))



@login_required
def evaluators(request, extra_context={}):

    if not request.user.is_admin:
        return HttpResponseNotFound('Sorry')

    form = EvaluatorUserCreationForm()

    evaluator_list = EvaluatorUser.objects.all()\
        .filter(is_active=True)\
        .exclude(pk=request.user.id)\
        .order_by('date_joined')\
        .reverse()

    context = {'evaluator_list': evaluator_list,
               'form': form,
               'modify_form': EvaluatorUserChangeForm(prefix="modificar")
               }

    context.update(extra_context)
    return render(request, 'eabmodel/evaluator.html', context)


@login_required
def add_eval(request):

    if not request.user.is_admin:
        return HttpResponseNotFound('Sorry')

    extra_context = {}
    if request.method != 'POST':
        form = EvaluatorUserCreationForm()
    else:
        form = EvaluatorUserCreationForm(request.POST)

        if form.is_valid():
            evaluator = form.save(commit=False)
            password = EvaluatorUser.objects.make_random_password()
            evaluator.set_password(password)
            evaluator.save()

            extra_context.update({'password': password, 'added_user': evaluator, "added_msg":True})
            form = EvaluatorUserCreationForm() # clean the form

    extra_context.update({'form': form})
    response = evaluators(request, extra_context)
    return response


@login_required
def remove_eval(request):

    if not request.user.is_admin:
        return HttpResponseNotFound("I don't know how you get here :s")

    if request.method == 'POST':
        form = EvaluatorUserRemoveForm(request.POST)
        if form.is_valid():
            evaluator = EvaluatorUser.objects.get(pk=form.cleaned_data['id'])
            evaluator.delete()
    return redirect(reverse('main:evaluators'))


@login_required
def modify_eval(request, eval=None):
    extra_context = {}

    if eval is not None:
        if not request.user.is_admin:
            return HttpResponseNotFound('Sorry')

        if request.method == 'POST':
            new_form = EvaluatorUserChangeForm(request.POST, instance=EvaluatorUser.objects.get(pk=eval), prefix="modificar" )
            if new_form.is_valid():
                new_form.save()
            extra_context.update({'modify_form': new_form})

    response = evaluators(request, extra_context)
    return response

eabmodel/templates/eabmodel/add_course.html
{% load static %}

<form action="{% url 'main:add_course' %}" method='post'>
  {% csrf_token %}
  {{ form }}
{#            <button name='submit'>Submit</button>#}
  <input type='submit' name='next' value="Submit" />
</form>

eabmodel/templates/eabmodel/ads.html
    <div id="modify" class="w3-modal" {% if modify_form.errors %} style="display:block !important {% endif %}">
      <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
        <div class="w3-center">
          <br>
          <span onclick="document.getElementById('modify').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
            <form class="w3-container" id="modificar-form" action="{% url 'main:modify_course' %}" method='post'>
              {% csrf_token %}
{#              {{ form.as_ul }}#}
              <div class="w3-section">
                {{ modify_form.non_field_errors }}
                {{ modify_form.name.errors }}
                <label for="{{ modify_form.name.id_for_label }}"><b>Nombre Curso:</b></label>
                {% render_field modify_form.name class+="w3-input w3-border w3-margin-bottom" placeholder=modify_form.name.label %}
                {#                {{ form.name }}#}
                {{ form.code.errors }}
                <label for="{{ form.code.id_for_label }}"><b>Código:</b></label>
{#                {{ form.code }}#}
                {% render_field modify_form.code class+="w3-input w3-border w3-margin-bottom" placeholder=modify_form.code.label %}
                {{ modify_form.section.errors }}
                <label for="{{ modify_form.section.id_for_label }}"><b> Sección </b></label>
{#                {{ form.section}}#}
                  {% render_field modify_form.section class+="w3-input w3-border w3-margin-bottom" placeholder=modify_form.section.label %}
                {{ modify_form.year.errors }}
                <label for="{{ modify_form.year.id_for_label }}"><b>Año</b></label>
{#                {{ form.year}}#}
                  {% render_field modify_form.year class+="w3-input w3-border w3-margin-bottom"%}
                {{ modify_form.semester.errors }}
                <label for="{{ modify_form.semester.id_for_label }}"><b>Semestre</b></label>
{#                {{ form.semester}}#}
                  {% render_field modify_form.semester class+="w3-input w3-border w3-margin-bottom"  %}
              </div>
              <input class="w3-button w3-block w3-red w3-section w3-padding"  type='submit' name='next' value="Modificar Curso +" />
            </form>
        </div>
      </div>
    </div><!-- cierra de modificar -->

eabmodel/templates/eabmodel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <title>Plataforma de evaluación</title>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <style>
      body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
      body {font-size:16px;}
      .w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
      .w3-half img:hover{opacity:1}
  </style>

  {% block head %}
  {% endblock %}

</head>

<body>

  <!-- Sidebar/menu -->
  <nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
    <!--Profile image -->
    <div class="w3-container">
      <p class="w3-center">
        <img src="https://www.w3schools.com/w3images/avatar3.png" class="w3-circle" style="height:150px;width:150px" alt="Avatar">
      </p>

    <h3 class="w3-padding-64"><center><b>
      {% if user.is_authenticated %}
      {{ user.first_name}} {{ user.last_name}}
      {% else %}
          Usuario
      {% endif %}

      </b></center></h3>
    </div>
    <div class="w3-bar-block">
      <a href="{% url 'main:landing_page' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a>
      <a href="{% url 'main:courses' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Cursos</a>

      {% if user.is_admin %}
        <a href="{% url 'main:evaluators' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluadores</a>
      {% endif %}

      <a href="{% url 'rubrica:index'  %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Rúbricas</a>
      <a href="{% url 'evaluacion:index'  %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluaciones</a>
      <a href="{% url 'contact:info' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Contact</a>

    </div>
  </nav>

    <!-- Top menu on small screens -->
  <header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
    <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
    <span>Usuario</span>
  </header>

  <!-- Overlay effect when opening sidebar on small screens -->
  <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

  {% block content %}
  {% endblock %}

</body>

<footer>
    {% block footer %}
    {% endblock %}

    <script>
        // Script to open and close sidebar
        function w3_open() {
          document.getElementById("mySidebar").style.display = "block";
          document.getElementById("myOverlay").style.display = "block";
        }

        function w3_close() {
          document.getElementById("mySidebar").style.display = "none";
          document.getElementById("myOverlay").style.display = "none";
        }

        // Modal Image Gallery
        {% comment %}function onClick(element) {
          document.getElementById("img01").src = element.src;
          document.getElementById("modal01").style.display = "block";
          var captionText = document.getElementById("caption");
          captionText.innerHTML = element.alt;
        }{% endcomment %}
    </script>

</footer>
</html>

eabmodel/templates/eabmodel/course.html
{% extends 'eabmodel/base.html' %}
{% load widget_tweaks %}
{% block head %}
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <style>
    table {
    border-collapse: collapse;
    }

    table, th, td {
      border: 1px solid black;
      text-align: left;
      padding: 3px;
    }

    #eliminar-msg {
      padding: 50px 0 50px 0;
    }
  </style>
{% endblock %}



{% block content %}
  <!-- !PAGE CONTENT! -->
  <div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Cursos</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
    <p><h3>Seleccione un curso</h3></p></h2>
  </div>

  <!-- Caja de Cursos -->
  <div class="w3-row-padding w3-center w3-margin-top">
    <!--Caja de agregar-->
  {% if user.is_admin %}
    <div class="w3-quarter w3-margin-top">
      <button onclick="document.getElementById('agregar').style.display='block'" class="w3-card w3-container w3-hover-shadow w3-light-gray" style="max-height:380px;min-height: 317px; width:200px">
        <h3 style="top: 0px">Agregar curso</h3><br><i class="fas fa-plus" style="font-size:100px"> </i>
      </button>
    </div>
  {% endif %}



    {%  for course in course_list %}
      <!--Caja Ejemplo -->
      <div id="{{ course.id }}"  class="w3-quarter w3-margin-top">
        <button onclick="document.getElementById('gestionar').style.display='block'" class="w3-card w3-container w3-hover-shadow w3-light-gray" style="max-height:380px;min-height: 317px; width:200px">
          <h3><span id="{{ course.id }}-name">{{ course.name }} </span></h3> <br> <i class="fas fa-book" style="font-size:100px"></i>
          <p> <span id="{{ course.id }}-code"> {{ course.code }}-{{ course.section }} </span> </p>
          <p> <span id="{{ course.id }}-year">{{ course.year }} </span>  <span id="{{ course.id }}-semester">{{ course.semester }} </span> </p>
          {% if user.is_admin %}
          <button class="w3-btn w3-red" onclick="modificarCourse(event)">Modificar</button>
          <button class="w3-btn w3-red" onclick="removeCourseConfirmation(event)"> Eliminar</button>
          {% endif %}
        </button>
      </div>
    {% endfor %}

    <!--Agregar -->
  {% if user.is_admin %}
    <div id="agregar" class="w3-modal" {% if form.errors %} style="display:block !important {% endif %}">
      <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
        <div class="w3-center">
          <br>
          <span onclick="document.getElementById('agregar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
            <form class="w3-container" action="{% url 'main:add_course' %}" method='post'>
              {% csrf_token %}
{#              {{ form.as_ul }}#}
              <div class="w3-section">
                {{ form.non_field_errors }}
                {{ form.name.errors }}
                <label for="{{ form.name.id_for_label }}"><b>Nombre Curso:</b></label>
                {% render_field form.name class+="w3-input w3-border w3-margin-bottom" placeholder=form.name.label %}
                {#                {{ form.name }}#}
                {{ form.code.errors }}
                <label for="{{ form.code.id_for_label }}"><b>Código:</b></label>
{#                {{ form.code }}#}
                {% render_field form.code class+="w3-input w3-border w3-margin-bottom" placeholder=form.code.label %}
                {{ form.section.errors }}
                <label for="{{ form.section.id_for_label }}"><b> Sección </b></label>
{#                {{ form.section}}#}
                  {% render_field form.section class+="w3-input w3-border w3-margin-bottom" placeholder=form.section.label %}
                {{ form.year.errors }}
                <label for="{{ form.year.id_for_label }}"><b>Año</b></label>
{#                {{ form.year}}#}
                  {% render_field form.year class+="w3-input w3-border w3-margin-bottom"%}
                {{ form.semester.errors }}
                <label for="{{ form.semester.id_for_label }}"><b>Semestre</b></label>
{#                {{ form.semester}}#}
                  {% render_field form.semester class+="w3-input w3-border w3-margin-bottom"  %}
              </div>
              <input class="w3-button w3-block w3-red w3-section w3-padding"  type='submit' name='next' value="Añadir Curso +" />
            </form>
        </div>
      </div>
    </div><!-- cierra de agregar -->


    <div id="modificar" class="w3-modal" {% if modify_form.errors %} style="display:block !important" {% endif %}>
      <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
        <div class="w3-center">
          <br>
          <span onclick="document.getElementById('modificar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
            <h2>Modificar Curso</h2>

            <form id="modificar-form" class="w3-container" action="{% url 'main:modify_course' %}" method='post'>
              {% csrf_token %}
{#              {{ form.as_ul }}#}
              <div class="w3-section">
                {{ modify_form.non_field_errors }}
                {{ modify_form.name.errors }}
                <label for="{{ modify_form.name.id_for_label }}"><b>Nombre Curso:</b></label>
                {% render_field modify_form.name class+="w3-input w3-border w3-margin-bottom" placeholder=modify_form.name.label %}
                {#                {{ form.name }}#}
                {{ modify_form.code.errors }}
                <label for="{{ form.code.id_for_label }}"><b>Código:</b></label>
{#                {{ form.code }}#}
                {% render_field modify_form.code class+="w3-input w3-border w3-margin-bottom" placeholder=modify_form.code.label %}
                {{ modify_form.section.errors }}
                <label for="{{ modify_form.section.id_for_label }}"><b> Sección </b></label>
{#                {{ form.section}}#}
                  {% render_field modify_form.section class+="w3-input w3-border w3-margin-bottom" placeholder=modify_form.section.label %}
                {{ modify_form.year.errors }}
                <label for="{{ modify_form.year.id_for_label }}"><b>Año</b></label>
{#                {{ form.year}}#}
                  {% render_field modify_form.year class+="w3-input w3-border w3-margin-bottom"%}

                {{ modify_form.semester.errors }}
                <label for="{{ modify_form.semester.id_for_label }}"><b>Semestre</b></label>
{#                {{ form.semester}}#}
                  {% render_field modify_form.semester class+="w3-input w3-border w3-margin-bottom"  %}

              </div>
              <input class="w3-button w3-block w3-red w3-section w3-padding"  type='submit' name='next' value="Modificar Curso +" />
            </form>
        </div>
      </div>
    </div><!-- cierra de modificar -->

    <!-- eliminar -->
    <div id="eliminar" class="w3-modal">
      <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px; min-height: 400px">
        <div id="eliminar-msg" class="w3-center">
          <span onclick="document.getElementById('eliminar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
            <h5 id="eliminar-text"></h5>
            <table style="margin:auto">
              <tr>
                <td>Nombre:</td>
                <td><span id="eliminar-text-name"></span></td>
              </tr>
              <tr>
                <td>Código:</td>
                <td><span id="eliminar-text-code"></span></td>
              </tr>
              <tr>
                <td>Año:</td>
                <td><span id="eliminar-text-year"></span></td>
              </tr>
              <tr>
                <td>Semestre:</td>
                <td><span id="eliminar-text-semester"></span></td>
              </tr>
            </table>
            <form class="w3-container" action="{% url 'main:remove_course' %}" method='post'>
                {% csrf_token %}
                <label for="id_id" type="hidden"></label>
                <input type="hidden" id="id_id" name="id" value="0">

            <input class="w3-button w3-red" style="margin:20px auto 0 auto" type='submit' name='next' value="Eliminar" />
            </form>
        </div>
      </div>
    </div> <!-- cierre de eliminar curso -->


  {% comment %}  <div id="modificar" class="w3-modal">
      <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px; min-height: 400px">
        <div id="modificar-msg" class="w3-center">
        </div>
      </div>
    </div>
  {% endcomment %}


  {% endif %}


    {% if added_msg %}
      <!-- Succesfully added message -->
      <div id="msg" class="w3-modal" style="display: block">
        <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px; min-height: 400px">
          <div class="w3-center">
            <span onclick="$('#msg').hide()" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
            <br>
            <h5>
            Curso Añadido Exitosamente!
            </h5>
            <table style="margin:auto">
            <tr>
                <td>Nombre:</td>
                <td><span> {{ added_course.name}} </span></td>
              </tr>
              <tr>
                <td>Código:</td>
                <td><span> {{ added_course.code }}</span></td>
              </tr>
              <tr>
                <td>Sección:</td>
                <td><span> {{ added_course.section }} </span></td>
              </tr>
              <tr>
                <td>Año:</td>
                <td><span>{{ added_course.year }}</span></td>
              </tr>

              <tr>
                <td>Semestre:</td>
                <td><span>{{ added_course.semester }} </span></td>
              </tr>


            </table>
            <button class="w3-button w3-red" style="margin:20px auto 0 auto"  onclick="$('#msg').hide(); $('#agregar').show()"> Añadir Nuevo </button>
          </div>
        </div>
      </div>
      <!--close added message -->

  {% endif %}

  </div><!--cierre de cajas de cursos-->
  </div>

{% endblock %}


{% block footer %}

  <script>
    function removeCourseConfirmation(e){
      let id = e.target.parentNode.id;
      $('#id_id').val(id);
      let name = $('#'+id+'-name').text();
      $('#eliminar-text-name').text(name);
      $('#eliminar-text-code').text($('#'+id+'-code').text());
      $('#eliminar-text-year').text($('#'+id+'-year').text());
      $('#eliminar-text-semester').text($('#'+id+'-semester').text());
      $('#eliminar-text').text( "Seguro deseas eliminar el curso " + name + "?");
      $('#eliminar').attr('style', 'display: block');;
      }


      function  modificarCourse(e) {
        let id = e.target.parentNode.id;

        $('#id_id').val(id);
        let name = $('#'+id+'-name').text();
        let code = $('#'+id+'-code').text();
        let c = code.split('-')[0].replace(" ","");
        let s = code.split('-')[1].replace(" ","");
        console.log(c);
        console.log(s);

        $('#modificar-form').attr("action", "{% url 'main:modify_course' %}/"+id);
        $('#id_modificar-name').val(name);
        $('#id_modificar-code').val(c);
        $('#id_modificar-section').val(s);
        $('#id_modificar-year').val($('#'+id+'-year').text().replace(" ",""));
        $('#id_modificar-semester').val($('#'+id+'-semester').text().replace(" ",""));
        $('#modificar').attr('style', 'display: block');

        {#$('#eliminar-text').text( "Seguro deseas eliminar el curso " + name + "?");#}
      }
  </script>

{% endblock %}